# Each route describes how an incomin URL will we processed by Platform.sh.

"https://www.{default}/":
    type: upstream
    upstream: "learning_log:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

    